export const Products_Mockeados = [
    {
      id: 1,
      category: 'Producto',
      name: 'Producto 1',
      description: 'Descripcion del Producto 1',
      price: '$10000',
      rating: 1,
      comments: 120,
      likes: 350,
      image: '',
    },
    {
      id: 2,
      category: 'Servicio',
      name: 'Producto 2',
      description: 'Descripcion del Producto 2',
      price: '$2000',
      rating: 2,
      comments: 89,
      likes: 230,
      image: '',
    },
    {
      id: 3,
      category: 'Comida',
      name: 'Producto 3',
      description: 'Descripcion del Producto 3',
      price: '$3000',
      rating: 3,
      comments: 156,
      likes: 420,
      image: '',
    },
    {
      id: 4,
      category: 'Producto',
      name: 'Producto 4',
      description: 'Descripcion del Producto 4',
      price: '$12000',
      rating: 4,
      comments: 75,
      likes: 180,
      image: '',
    },
    {
      id: 5,
      category: 'Servicio',
      name: 'Producto 5',
      description: 'Descripcion del Producto 5',
      price: '$200000',
      rating: 5,
      comments: 210,
      likes: 550,
      image: '',
    },
  ];